Server:
  host: 121.248.12.116
  username: root
  password: 123568
  port: 6316
  servlet:
    context-path: /sds
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sds?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123568
mybatis:
  mapper-locations: mybatis/mapper/*.xml

Iperf:
  A:
    ip: 192.127.10.2
    port: 22
    username: root
    password: 123456
  C:
    ip: 192.127.12.1
    port: 8081
    username: root
    password: 123456
  remote: /home/sender/iperf3_file/
  testPort:  26316
Component:
  B:
    ip: 47.98.228.148
    port: 22
    username: root
    password: yjj0413_Aly
