Server:
  servlet:
    context-path: /sds
  port: 6316
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sds?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123568
mybatis:
  mapper-locations: mybatis/mapper/*.xml

Iperf:
  A:
    ip: 47.98.228.148
    port: 22
    username: root
    password: yjj0413_Aly
  C:
    ip: 47.98.228.148
    port: 22
    username: root
    password: yjj0413_Aly
Component:
  B:
    ip: 47.98.228.148
    port: 22
    username: root
    password: yjj0413_Aly
    remote: /home